# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from chat_protobufs import chatroom_pb2 as chatroom__pb2


class ChatStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.messageStream = channel.unary_stream(
                '/Chat/messageStream',
                request_serializer=chatroom__pb2.Nothing.SerializeToString,
                response_deserializer=chatroom__pb2.sendMessageRequest.FromString,
                )
        self.sendMessage = channel.unary_unary(
                '/Chat/sendMessage',
                request_serializer=chatroom__pb2.sendMessageRequest.SerializeToString,
                response_deserializer=chatroom__pb2.Nothing.FromString,
                )
        self.connectedUser = channel.unary_unary(
                '/Chat/connectedUser',
                request_serializer=chatroom__pb2.connectionRequest.SerializeToString,
                response_deserializer=chatroom__pb2.connectionConfirm.FromString,
                )


class ChatServicer(object):
    """Missing associated documentation comment in .proto file."""

    def messageStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def connectedUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'messageStream': grpc.unary_stream_rpc_method_handler(
                    servicer.messageStream,
                    request_deserializer=chatroom__pb2.Nothing.FromString,
                    response_serializer=chatroom__pb2.sendMessageRequest.SerializeToString,
            ),
            'sendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.sendMessage,
                    request_deserializer=chatroom__pb2.sendMessageRequest.FromString,
                    response_serializer=chatroom__pb2.Nothing.SerializeToString,
            ),
            'connectedUser': grpc.unary_unary_rpc_method_handler(
                    servicer.connectedUser,
                    request_deserializer=chatroom__pb2.connectionRequest.FromString,
                    response_serializer=chatroom__pb2.connectionConfirm.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Chat', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Chat(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def messageStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Chat/messageStream',
            chatroom__pb2.Nothing.SerializeToString,
            chatroom__pb2.sendMessageRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Chat/sendMessage',
            chatroom__pb2.sendMessageRequest.SerializeToString,
            chatroom__pb2.Nothing.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def connectedUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Chat/connectedUser',
            chatroom__pb2.connectionRequest.SerializeToString,
            chatroom__pb2.connectionConfirm.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
